### ISSUE TITLE
Include concordances in response?

### ISSUE THREAD

**Issue by kochis** [whosonfirst/go-whosonfirst-pip-v2#33]
Is there a way to include the concordances in the response? 

Seems like this would probably need to happen during the index phase, not sure if there was an easy way to configure this or not.

Thanks!

**Comment by thisisaaronland** [comment]
The closest thing would be using the experimental "extras" feature:

https://github.com/whosonfirst/go-whosonfirst-pip-v2#extras

That work hasn't been touched in a long time so it might be a bit wobbly.

**Comment by kochis** [comment]
Yeah, I was looking at that. I’ll take a stab and see how it works out. Thanks for the quick response.

**Comment by thisisaaronland** [comment]
The PIP codebase is overdue a bit of a refactoring so any comments, suggestions and (gentle :-) cluebats about things, and the extras in particular, stuff are welcome.

**Comment by kochis** [comment]
Starting with `-enable-extras` was able to do the trick (along with the `extras=wof:*` param)
